### ISSUE TITLE
steps_python_bin should not default to python_bin

### ISSUE THREAD

**Issue by asottile** [Yelp/mrjob#1038]
This says it falls back to sys.executable:
http://mrjob.readthedocs.org/en/latest/guides/configs-all-runners.html#option-steps_python_bin

The code says otherwise:
https://github.com/Yelp/mrjob/blob/4a66b1c0ee12d540b2e3d6f43391cae6b9bc6ca1/mrjob/runner.py#L241-L243

**Comment by davidmarin** [comment]
Yep, good catch. The docs are out-of-date.

**Comment by davidmarin** [comment]
Oh, no, never mind. Look carefully at the code. If `local=True` (which it does for `steps_python_bin`), `_default_python_bin()` does indeed return `[sys.executable]`.

**Comment by asottile** [comment]
@davidmarin correct.  But the code I highlighted says `self['python_bin'] or self._default_python_bin(local=True))`

which is making it quite difficult when I want my remote python to be a virtualenv's python and I want my local python to be sys.executable

**Comment by davidmarin** [comment]
Ah, I see, you want to be able to set `python_bin` without changing `steps_python_bin`. That sounds reasonable. Because it changes the defaults, I'm going to save this for v0.5.0 (which will come out about the same time as v0.4.5 anyway).

**Comment by asottile** [comment]
It only changes the defaults if you're modifying python_bin so it probably has less of an impact, but sure 5.0 will be fine.

For now I'm working around it with this:

```yaml
    python_bin: /home/hadoop/virtualenv_run/bin/python
    # Hack until https://github.com/Yelp/mrjob/issues/1038
    steps_python_bin: python
```

**Comment by davidmarin** [comment]
Yep, that is the workaround. Honestly, v0.4.5 mostly exists to get in those last few deprecation warnings, so it'll be coming out about the same time as v0.5.0.

And yeah, debatably this is a bug because it contradicts the docs. I just remember having what I thought was a good reason for making it work that way when when I wrote that code. It's really more of a suboptimal design decision, and that should wait for a major release.

**Comment by davidmarin** [comment]
Aha! This goes back to when we were introducing partial support for scripts in other languages to mrjob. If you wanted to run, say, a job written in Ruby, you'd set `interpreter` to `ruby`, and `steps_interpreter` would also be set to `ruby` automatically.

This makes less sense for `python_bin` and `steps_python_bin` (because `sys.executable` is almost always right), but that's the reasoning.

**Comment by davidmarin** [comment]
Working on this now.
