### ISSUE TITLE
read previous step output into distributed cache

### ISSUE THREAD

**Issue by tianhuil** [Yelp/mrjob#1066]
Currently, I believe there is no (easy) way to specify a job that normalizes feature values (e.g. for machine learning).  For example, if we have a file where each row is a value $X_k$ and we want
$\frac{X_k}{ \sum_k X_k}$,
the only solution is to output the sum in a mapreduce and then feed this sum file and the original file into a second mapreduce (via a distributed cache mechanism).  This is also commonly used for map-side join.s

Some simple support for reading and writing from the cache would be great!

**Comment by davidmarin** [comment]
mrjob definitely supports distributed cache. :)

For your use case, I think you want [add_file_option()](https://pythonhosted.org/mrjob/guides/writing-mrjobs.html#file-options).

**Comment by tianhuil** [comment]
Hi @davidmarin: but `add_file_option` does not appear to support the use case I'm mentioning.  I would like to write the sum of all the values to the distributed cache after the mapper and use them for the reducer or in subsequent steps.  `add_file_option` appears to only support initializing at `MRJob` start and then reading in all mappers and reducers.

**Comment by davidmarin** [comment]
Shoot, I wasn't aware that Hadoop Streaming jobs *could* write to the Distributed Cache.

You might try writing to HDFS directly?

**Comment by tianhuil** [comment]
Hi,

I know this is certainly possible in Hadoop.  Is there a recommended way of mapping $X_k$ to
$\frac{X_k}{ \sum_k X_k}$?

Michael

**Comment by davidmarin** [comment]
I admit this is something I don't know much about. How would you do it in Hadoop?

**Comment by tianhuil** [comment]
So this is what we did at 4sq: 2 map-only MR jobs:

The first one would output the sum (computed mapside).
The second one would read that s3 location from HDFS.

At 4sq, we would have glued them together using luigi to handle inputs and
ouputs.  But MRJob doesn't support this without using an external gluing
service (e.g. luigi).  Since it attempts to provide the "gluing", it would
be wonderful if MR job had a way (even a hack) for outputting to s3 (or
HDFS) and then reading it in via the distributed cache.

**Comment by davidmarin** [comment]
Ah, okay, so you're not actually writing back to the Distributed Cache, you're loading the output of one job into the distributed cache for another job.

I think the problem with making this a mrjob feature is that there are lots of ways to do this, and which one is best depends on your particular situation.

Did you know that you can [run mrjobs from Python code](https://pythonhosted.org/mrjob/guides/runners.html#running-your-job-programmatically). That's usually the way to do this sort of thing.

And I see what you're saying, that this is conceptually a single job with an unusual way of passing data between steps, and that mrjob supports multi-step jobs, so it'd make sense to support this. We're just not there right now. At some point, we may consider supporting DAGs of jobs, and then this sort of thing makes sense.

Also, a practical question: how did you end up with a single "sum" file, rather than one for each mapper?

**Comment by tianhuil** [comment]
Thanks David - this solves my problem!  I did not know about being able to
run mrjobs from Python code, so that seems to solve it nicely.  At 4sq,
there was a "single shard" utility MR.  For MR job, I would probably
tolerate the small number of files and do some sort of pythonic tweaking in
the "outer" python glue code to coerce that into the distributed cache
(will read up on this shortly).

**Comment by davidmarin** [comment]
Cool. Closing this for now.
