### ISSUE TITLE
could open ssh tunnel earlier

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#1115]
If we're connected to a cluster with a job already running, we should still be able to get at the job tracker/resource manager before our job starts running.

**Comment by kkazlowski** [comment]
I don't know if this is related, but I have a job that seems to remain in the "PENDING" state (per `step.status.state`, whereas the cluster has gone from "STARTING" to "BOOTSTRAPPING" to "RUNNING" (per `cluster.status.state`).

Found this via our logging in emr.py, around line 1550. 

Due to the `step.status.state` not being "RUNNING", we're not opening the ssh tunnel to the job tracker.

**Comment by davidmarin** [comment]
Yeah, that's pretty much the issue.

Does your step eventually enter the `RUNNING` state? If not, that's a bigger problem that not being able to reach the resource tracker.

**Comment by kkazlowski** [comment]
One of my jobs just seems to be stuck in `PENDING`. Though another makes it through just fine, and I do get access to the resource manager for that one. They're configured identically in terms of mrjob.conf, just different python jobs. Though I know for a fact that both work just fine on mrjob-0.4.4.
