### ISSUE TITLE
EMR Bootstrap Command Failure on 2.x AMIs/Debian 6

### ISSUE THREAD

**Issue by solumos** [Yelp/mrjob#1246]
Somewhat related to #1214, as those docs are no longer entirely valid - Debian 6 (Squeeze) was removed from LTS on 2/29 (https://wiki.debian.org/LTS). This created broken packages that prevented installing `python-pip` as a bootstrap command (using mrjob v0.4.6).

Firstly,
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-pip : Depends: python (>= 2.6.6-7~) but 2.6.6-3+squeeze7 is to be installed
              Recommends: python-dev-all (>= 2.6) but it is not installable
              Recommends: build-essential but it is not going to be installed
```
And trying `sudo apt-get update`:
```
Err http://http.us.debian.org squeeze/main amd64 Packages
  404  Not Found [IP: 64.50.236.52 80]
Err http://http.us.debian.org squeeze/contrib amd64 Packages
  404  Not Found [IP: 64.50.236.52 80]
Err http://http.us.debian.org squeeze/non-free amd64 Packages
  404  Not Found [IP: 64.50.236.52 80]
```
Simply updating our process to use AMI 3.11 and updating `ec2-master-instance-type` fixed this issue for us, however it would be nice to have some notes about this problem in the docs.

**Comment by alejandro-rivera** [comment]
It has to be said that this is not a mrjob issue, but an issue with the `2.4.x` AMI series, due to the Debian version they provide.

If for some reason you need to stick with `2.4.x` AMIs, you can do the following to have pip available system-wide:

1. Download the official **get-pip.py** file into a location that can be referenced by your mrjob project (e.g. `cd myproject; wget https://bootstrap.pypa.io/get-pip.py`)
2. Replace the `sudo apt-get install -y python-pip` bootstrap action with a new one that runs the **get-pip.py** script (e.g. `--bootstrap 'sudo python get-pip.py#'`). Note the hash sign at the end of the filename, it's important to include it.

And that's it.

Cheers.

**Comment by solumos** [comment]
Cool, thanks David - definitely not expecting major code-level changes to support deprecated configs. Just wanted to push for some documentation around this.

Thanks,

Tom Hadley

**Comment by davidmarin** [comment]
Not going to add a workaround to mrjob, but the docs explain what to do if you must continue installing packages on 2.x AMIs:

    https://pythonhosted.org/mrjob/guides/emr-bootstrap-cookbook.html#x-amis
