### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [Yelp/mrjob#1356]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like _mrjob_, deleted their software history.

https://github.com/Yelp/mrjob/commit/3a1b1e8ac30833479aab6dfbfc462f334487575a

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask mrjob developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by davidmarin** [comment]
Oh, yay, software engineering research. That’s what I did in grad school (see https://www.eecs.berkeley.edu/Pubs/TechRpts/2005/EECS-2005-18.html)

The reason for not keeping the software history is pretty simple; mrjob started out as a package in Yelp’s proprietary code (yelp-main), that was entangled with this proprietary code. It wasn’t so much a matter of deleting the history as disentangling mrjob from yelp-main and copying the disentangled code into its own git repo.

My guess is that this pattern is pretty common for Open Source projects; first get something working, and then disentangle it from your own proprietary code, configuration, etc. Might be interesting to try to quantify this (for example, I’d hypothesize that Open Source projects from industry that started out as internal code are more likely to be successful than industry Open Source projects that started from scratch, for some metric of success).

In answer to the last three questions, there wasn’t really any consequence to not having the history in the public repo. I was the only mrjob developer at the time, and had access to both repos. I don’t think I ever referred to the pre-release history of mrjob, though since that was almost 6 years ago now, I might have forgotten.

Hope this helps!

**Comment by gustavopinto** [comment]
Hi @davidmarin,

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
