### ISSUE TITLE
JAVA_HOME containing spaces results in failed job?

### ISSUE THREAD

**Issue by eugenio11** [Yelp/mrjob#1581]
Hello,
I'm working locally on Mac OS, using python 2.7.

I am testing this script:
http://hadoopgeek.com/mapreduce-movie-recommendation/

and I launch the job via: 
python mapreduce.py -r hadoop --hadoop-bin /Users/my_path_to_hadoop/bin/hadoop --items hdfs://localhost:9000/user/eugenio/u.item hdfs://localhost:9000/user/eugenio/u.data2 > results.txt

but the job fails with the error "returned non-zero exit status 256".

Looking at the logs, I see
/bin/bash: /Library/Internet: No such file or directory

I think the problem is related to my JAVA_HOME, which is (copy/paste from hadoop-env.sh)
export JAVA_HOME=/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

(as you can see, it contains a blank space).

I've tried to create a symbolic link (without blank spaces) but the problem remains. Any clue?

Thanks.

Thanks.

**Comment by davidmarin** [comment]
Huh, it does look like the blank space is causing a problem somewhere inside Hadoop. Surprised that the symlink doesn't fix it!

Closing this because this seems to be more about how to set up a local Hadoop structure than anything about mrjob. I think Stack Overflow etc. will probably be more help here than I will.

I'm a little surprised that mrjob wasn't able to find that message in the logs for you though. Where are your logs located? Do the `hadoop fs` commands work?

**Comment by eugenio11** [comment]
Hello,
I don't think it is hadoop-related, hadoop is working, at least I can work with the hadoop file system without any problem.
