### ISSUE TITLE
AWS/EMR cluster terminates with instance failure error status with terminate_idle_cluster.sh

### ISSUE THREAD

**Issue by okomestudio** [Yelp/mrjob#1725]
I'm currently evaluating a migration to mrjob v0.6.x (from v0.5.x) and I understand that idle cluster termination for v0.6.x is now done as a bootstrap script run as a background process via `sudo shutdown -h now`.

Unfortunately, this appears to cause AWS/EMR cluster to shutdown with a `Terminated with errors`/`Instance failure` state. This gives an appearance that something went wrong with the cluster. Is there another way to shut it down more gracefully?

Looking at the code, this does not seem like a bug per se and certainly nothing major, but it looks confusing when the cluster termination status ends with an instance failure when it was actually done as intended and in some cases not desirable (e.g., when some action gets triggered based on cluster termination status).

**Comment by davidmarin** [comment]
If there is, I wasn't able to find it. For a "clean" shutdown, the cluster would need to access the EMR API, which would introduce a fair amount of complication and security issues. I've certainly asked people on the EMR team for such a feature, but no luck (Google Cloud Dataproc has one though!).

The simplest solution is to just stop using pooling and instead let the cluster shut itself down after your job runs. AWS now bills by the minute rather than the full hour, so cluster pooling is no longer a cost-saving measure.

Alternatively, you can continue running `mrjob terminate-idle-clusters` and have it terminate clusters before they terminate themselves. Unfortunately, I messed up the code for setting `max_mins_idle` in the config file (see #1726, which will be fixed in the next release), but the command line (`--max-mins-idle 20`) works.

Finally, if I remember correctly, there is a CloudWatch alert for Hadoop being idle, but I was unable to hook it up with the shutdown action (it would only send emails). This was a couple of years ago at this point, so it might be worth looking into, if you're using CloudWatch anyhow.
