### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by rizplate** [Yelp/mrjob#1740]
Is it possible to package the job as docker i.e. can the AWS EMR run a docker job? either with mesos/kubernetes or without it?

**Comment by davidmarin** [comment]
Yes.

One way is to make a setup script that wraps your job, so that instead of just invoking Python to run your job, it sets up a Docker instance and runs your job inside it. There isn't an off-the-shelf solution for this because the bulk of the setup script has to do with the details of setting up your Docker instance.

Instead of using a setup script, you could also set `python_bin` to be a script that setups up Docker and then invokes python. That's probably a better solution; it should work with Spark as well as streaming jobs, and you don't have to worry about the setup script boilerplate that mrjob generates.

FYI, whatever method you choose, I recommend piping your job's stderr and stdout through FIFOs rather than just sending them through the Docker util's stderr and stdout; this seems to be a lot slower for whatever reason.
