### ISSUE TITLE
google-cloud 0.33.0 is broken

### ISSUE THREAD

**Issue by joergrech** [Yelp/mrjob#1780]
When I start a cluster on EMR it is cancelled due to a problem in mrjob when it loads the google-cloud dependencies. It looks like it started yesterday with a new deployment of "google-cloud" python package. I've created a issue which might be helpful to you: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5353

The Error was:
```
...
Collecting google-cloud>=0.32.0 (from mrjob)
  Downloading https://files.pythonhosted.org/packages/49/9a/943f0e217990c37e119101bbb739d86201ec1fdf59152ecc2dba93c5a8ad/google-cloud-0.33.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/mnt/tmp/pip-build-P0PK73/google-cloud/setup.py", line 22, in <module>
        with open(os.path.join(PACKAGE_ROOT, 'setup-README.rst')) as file_obj:
    IOError: [Errno 2] No such file or directory: '/mnt/tmp/pip-build-P0PK73/google-cloud/setup-README.rst'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /mnt/tmp/pip-build-P0PK73/google-cloud

(from lines 14-43 of s3://tw-emr-synonyms/tmp/logs/j-G6AEP8ORKNR2/node/i-016376a9dc3b31913/bootstrap-actions/1/stderr.gz)
...
```

**Comment by davidmarin** [comment]
It looks `google-cloud` 0.33.0 is just broken. There wasn't really a way for mrjob to anticipate this (since `google-cloud` 0.33.0 didn't exist when mrjob came out), but the workaround is to `pip install google-cloud 0.32.0`.

I'll exclude this broken version of `google-cloud` in mrjob 0.6.3.

**Comment by joergrech** [comment]
OK it looks like it works now with 0.33.1 (see https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5353#issuecomment-391114891).

I tested it on EMR right now and it works!

Btw. is sound that mrjob should not need "google-cloud" in Amazon EMR - probably only in GCP. Is there a way to control which dependencies are loaded depending on the cloud/environment they are run in? (Please note that I'm relatively new to Python and do not know which functionality mrjob is using from this package)

**Comment by davidmarin** [comment]
Yeah, `google-cloud` is way too general. It was originally included to cover up conflicts with the overly strict dependencies of `google-cloud-dataproc` 0.10.0, but now that doesn't even help because it needs a newer version of `google-cloud-storage`.

I'm currently waiting on a new, better version of `google-cloud-dataproc`, and if that doesn't happen, I'm going to be forced to move the google stuff to a sub-dependency. So instead of `pip install mrjob`, you'd do `pip install mrjob[google]==0.6.3`.

However, mrjob has never had optional dependencies before, and I'd rather not go that route if I don't have to, for the same reason I wouldn't want to disable AWS support by default.

For more information, see #1746.
