### ISSUE TITLE
--libjar option

### ISSUE THREAD

**Issue by irskep** [Yelp/mrjob#198]
Currently, using `-libjars` requires something like this:

    --bootstrap-file myjar.jar --bootstrap-cmd 'cp myjar.jar /home/hadoop/myjar.jar' --hadoop-arg -libjars --hadoop-arg /home/hadoop/myjar.jar

It would be nice if we could do this instead:

    --libjar myjar.jar

mrjob would:

* Upload the file like the other bootstrap files
* Copy it to a unique location like /tmp/myjar-235324.jar
* Add the appropriate `-libjars` argument to `StreamingStep.step_args`

**Comment by davidmarin** [comment]
Looks pretty straightforward. We should also add this for the Hadoop runner, though it's much simpler there.

**Comment by davidmarin** [comment]
Should also allow `file:///` URIs for JARs on the cluster.

**Comment by davidmarin** [comment]
Looks like bootstrap actions run in `/mnt/var/lib/bootstrap-actions/<action_num>`, not `/home/hadoop` (`<action_num>` is 1-indexed). So copying them is the right way to go.

So as not to interfere with other bootstrap actions, we should probably copying them into `/home/hadoop/mrjob-<random_hex>` or some such.

**Comment by davidmarin** [comment]
`/tmp/mrjob-<random_hex>` seems like a safe bet.

**Comment by davidmarin** [comment]
Might want to just designate a subdirectory of `/tmp` as the working directory for bootstrap scripts, rather than maintaining a separate subdirectory for JARs.

In theory, we could guess the working directory for the master bootstrap script, but this is frustrated by AMIs that use bootstrap actions to apply security patches. So we wouldn't know what to put in the bootstrap script until after we'd launched the cluster and inspected it, but we couldn't launch the cluster until we knew what to put in the bootstrap script!

**Comment by davidmarin** [comment]
`/home/hadoop/mrjob-jars-<random_hex>` seems safer, somehow. Going to go with that for now.

**Comment by davidmarin** [comment]
Bootstrap time isn't really the right time to do this, since libjars might differ from job to job.

We really need a mechanism for getting files shipped to a predictable location prior to running a job's steps (`/home/hadoop/<job key>` maybe?). We could do this with `script-runner.jar`, though of course that adds a step to our job, which (*\*sigh\**) affects pooling.

Probably want to call this mechanism `master_node_setup` or some such. Presumably it'd be useful to someone to expose this, but I don't want to create confusion with the setup and bootstrap scripts.

**Comment by davidmarin** [comment]
Was able to get a job running from inside EMR with [nicknack](https://github.com/empiricalresults/nicknack). Now let's make it easy!

**Comment by davidmarin** [comment]
Tried running a job with `-libjars` on HDFS (on Hadoop 2.4.0 on a 3.7.0 AMI on EMR). Didn't work; you get a warning like this:

```
  The libjars file hdfs://172.31.19.27:9000/user/hadoop/nicknack-1.0.0.jar is not on the local filesystem. Ignoring.
```

**Comment by davidmarin** [comment]
Might be good to be aware of [MAPREDUCE-289](https://issues.apache.org/jira/browse/MAPREDUCE-6289), which breaks `-libjars` when running Hadoop in pseudo distributed mode. (This isn't something mrjob can really work around, and "real" clusters don't run in pseudo distributed mode.)
