### ISSUE TITLE
Python 3.3 compatibility (except EMR)

### ISSUE THREAD

**Issue by irskep** [Yelp/mrjob#217]
The goal of this ticket is a full port of mrjob that works for everything except EMR. This includes tests.

Roadmap:

* v0.4.2: Last release to support 2.5
* v0.4.4: Experimental support for Python 3, except EMR
* v0.5.0: Full support for Python 3.

This does not include EMR support (#989) or updating docs and examples (#994).

**Comment by bonitao** [comment]
Hi @irskep,

I have finished the work started by @edschofield. I have forked his repo, and you can see the remaining changes for python 3 compatibility here: https://github.com/bonitao/mrjob/tree/py3.

The changes are all sort of straightforward, and the biggest headache is python 3 improved discipline on encodings. You can pull my repository, but since there may be too many changes, I will be happy to send you piecemeal, logically contained, commits if you prefer. 

All tests pass in python2 and python3, and I have ran a few jobs locally or inline. I have not tried it on aws yet though, but I will do it in the next few weeks.

**Comment by irskep** [comment]
Thanks! I think @anusha-r is the current maintainer who will need to look at it.

**Comment by davidmarin** [comment]
Realized `assertItemsEqual()` won't work on Python 3.

**Comment by davidmarin** [comment]
Fixed by #1007
