### ISSUE TITLE
SkipBadRecords --- missing in mrjob?

### ISSUE THREAD

**Issue by ghost** [Yelp/mrjob#361]
Is there a way to utilize Hadoop's SkipBadRecords functionality using mrjob?

RIght now, for a particular job, I'm running my map and reduce steps separately because there are a couple bad records that get caught in the map step and cause reduce to get canceled entirely.

Did I just not read the right tutorial?   Or is this feature missing?  Or is it not possible in streaming?  

I can work on a patch if someone points me in the right direction.

Thanks.

**Comment by uttara-cmu** [comment]
Hi,

I have been trying to use --jobconf in my code with different values for mapred.skip.map.max.skip.records. This doesn't seem to work, i.e, I am still getting a Hadoop error for bad records.

python map_coords.py -r emr s3://twitter-uttara-std/test-folder/2013_03/tweets.2013-03-21* s3://twitter-uttara-std/test-folder/2013_03/tweets.2013-03-22* s3://twitter-uttara-std/test-folder/2013_03/tweets.2013-03-23*  --conf-path mrjob_sep.conf --jobconf mapred.skip.mode.enabled=true --jobconf mapred.map.max.attempts=5 --jobconf mapred.reduce.max.attempts=5 --jobconf mapred.skip.map.max.skip.records=30 --jobconf mapred.skip.attempts.to.start.skipping=1 > output_2013_03_21_23

I keep getting the same error regardless of whether I pass in the jobconf parameters or not. I tried varying the values and also tried following http://devblog.factual.com/practical-hadoop-streaming-dealing-with-brittle-code. i.e, I added parameters to jobconf and also added "sys.stderr.write('reporter:counter:SkippingTaskCounters,MapProcessedRecords,1')" in my code. I still keep getting the same error and I am not able to make Hadoop skip bad records.

Task: attempt_1483495435864_0001_m_001032_0 - exited : java.io.IOException: invalid distance code

        at org.apache.hadoop.io.compress.zlib.ZlibDecompressor.inflateBytesDirect(Native Method)

        at org.apache.hadoop.io.compress.zlib.ZlibDecompressor.decompress(ZlibDecompressor.java:228)

        at org.apache.hadoop.io.compress.DecompressorStream.decompress(DecompressorStream.java:91)

        at org.apache.hadoop.io.compress.DecompressorStream.read(DecompressorStream.java:85)

        at java.io.InputStream.read(InputStream.java:101)

        at org.apache.hadoop.util.LineReader.fillBuffer(LineReader.java:180)

        at org.apache.hadoop.util.LineReader.readDefaultLine(LineReader.java:216)

        at org.apache.hadoop.util.LineReader.readLine(LineReader.java:174)"

Has anything changed in this since 2012? What should I be doing?


Thanks
Uttara

**Comment by davidmarin** [comment]
Huh, I thought that the problems was that you're using Hadoop 1 property names on Hadoop 2, but it looks like all the names you use are automatically translated by mrjob.

My guess from reading your stack trace is that your compressed file is corrupt, not that there's one or two bad lines in the uncompressed data.

I don't know offhand if Hadoop has a property that would enable this for streaming jobs. [This article] shows how to deal with the problem when writing jobs in Java; it might be a good starting point at least.

**Comment by davidmarin** [comment]
Also, mrjob should tell you which input file it failed on. mrjob actually has the code to parse all the logs for your job and find all the input files it failed on, though that's not exposed. Would that be useful as a future feature?

**Comment by uttara-cmu** [comment]
Thanks for the reply. Yeah, I see MRjob auto translating the old property names on my logs. I will check that link. Looks useful.

Yes, showing which files are problematic would be a tremendously helpful feature. I have Twitter files sampled every 15-minutes for a whole bunch of years and I really don't care about missing some intervals as long as I know which ones are faulty. Right now, I keep running mrjob in small batches until the job fails and this is taking a long time to find out which files are problematic.
Do you want me to file a feature request?

**Comment by davidmarin** [comment]
Sure. It'd be great to have a use case.

You could probably also sniff out the bad files using a specially designed job that takes as input a manifest file where each line contains the path of a (possibly corrupt) input file, and then your mapper downloads that file and tries to uncompress it, emitting the file's path on failure.

**Comment by uttara-cmu** [comment]
Thanks so much for the suggestion to write a separate special job that takes in input from a manifest file. Worked like a charm. I had one corrupt file every month (among the 2700 odd files every month) and once I removed this bad apple, my original job ran without errors. It would have taken a lot of trial and error to narrow it down to a single corrupted file. Thanks for saving me a lot of time! :-)

**Comment by davidmarin** [comment]
Glad I could help!
