### ISSUE TITLE
*_cmds should run in a subshell

### ISSUE THREAD

**Issue by davidmarin** [Yelp/mrjob#837]
For full compatibility with the way `setup_cmds` etc. were run when we used python scripts for setup, we should run these commands in a subshell (that is, the wrapper script should put parentheses around each command), so that the effect of `cd` and `export` is temporary.

**Comment by anusha-r** [comment]
@davidmarin : can you elaborate this issue? Not sure I understand.

**Comment by davidmarin** [comment]
Sure. If you have a setup_cmd like `mkdir /tmp/foo; cd /tmp/foo; touch bar` and another one like `touch baz`, the second command will also run from inside `/tmp/foo` as well.

Whereas what we want is for each setup_cmd to be independent; the final working directory of the first setup_cmd shouldn't propagate to the next one.

In sh, to execute commands in a subshell, you just put them inside `()`. In principle, this is a really easy change; I just didn't have the time/energy to test it.

**Comment by anusha-r** [comment]
Thanks @davidmarin. 

Made the appropriate changes but some of the tests that change PYTHONPATH using --setup started failing (eg: test_runner.test_python_archive) - probably a side effect we did not consider? 

Also, our guides walk through some examples where multiple --setup options are chained together (eg: http://mrjob.readthedocs.org/en/latest/guides/setup-cookbook.html#running-a-makefile-inside-your-source-dir). Making the change mentioned here will change this behavior and I'm not sure if that's warranted since we have a workaround (adding "()" when passing commands to setup)

**Comment by davidmarin** [comment]
Good point.

Thinking we should probably consider the current behavior a feature rather than a bug. Adding `()` is a good workaround.

Closing this ticket.
